### ISSUE TITLE
Transactions history csv file example

### ISSUE THREAD

**Issue by kuatroka** [simprecicchiani/iPortfolio#2]
Hi, thanks for the app. In the app UI, there is an option to drop CSV file with transactions, which looks very comfortable, but could you please provide a sample of what the CSV file should look like? What is the format, schema/columns, values examples. Thanks

**Comment by simprecicchiani** [comment]
Hi, I’m glad you’re liking it. I will add a sample csv file. Meanwhile, you could add a transaction manually, use the download transactions file  button and see what that file looks like.

**Comment by kuatroka** [comment]
Thank  a lot. Will do
